Server/Models/Testperson.cs
using System.Data;
using System.Threading.Tasks;
using MySqlConnector;
using System.ComponentModel.DataAnnotations;

namespace UIAutomate.Models{
    
    public class Testperson
    {
        [Key]
        public int Id { get; set; }

        public string anonymName {get; set; }

        public List<SUSTest> SUSTests {get; set;} = new List<SUSTest>();
        public List<UEQTest> UEQTests {get; set;} = new List<UEQTest>();
        public List<VisAWITest> VisAWITests {get; set;} = new List<VisAWITest>();

    }
}

Server/Controllers/TestpersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIAutomate.Models;

namespace Server.Controllers
{
    public class TestpersonController : Controller
    {
        private readonly TestpersonContext _context;

        public TestpersonController(TestpersonContext context)
        {
            _context = context;
        }

        // GET: Testperson
        public async Task<IActionResult> Index()
        {
              return View(await _context.Testpersons.ToListAsync());
        }

        public async Task<IActionResult> Introduction()
        {
            return View(await _context.Testpersons.ToListAsync());
            //   return _context.SUSTest != null ? 
            //               View(await _context.SUSTest.ToListAsync()) :
            //               Problem("Entity set 'SUSTestContext.SUSTest'  is null.");
        }

        // GET: SUSTest/Edit/5    duplicatet
        public async Task<IActionResult> SUSResults()
        {
            // if (id == null || _context.SUSTest == null)
            // {
            //     return NotFound();
            // }

            IEnumerable<SUSTest> sUSTest = _context.SUSTests.FromSqlRaw<SUSTest>(@"SELECT * FROM SUSTests WHERE TestpersonId == 1;").ToList<SUSTest>();
            if (sUSTest == null)
            {
                return NotFound();
            }
            return View(sUSTest);
        }

        public IEnumerable<SUSTest> DataSeeder(){
                 var cmd = _context.SUSTests.FromSqlRaw<SUSTest>(@"SELECT * FROM SUSTests WHERE TestpersonId == 1;").ToList<SUSTest>();
            return cmd as IEnumerable<SUSTest>;
        }

        public async Task<IActionResult> VisAWIFormular()
        {
            IEnumerable<VisAWITest> vis = _context.VisAWITests.FromSqlRaw<VisAWITest>(@"SELECT * FROM VisAWITests WHERE TestpersonId == 1;").ToList<VisAWITest>();
            if (vis == null)
            {
                return NotFound();
            }
            return View(vis);
        }

        
        public async Task<IActionResult> UEQFormular()
        {
            IEnumerable<UEQTest> vis = _context.UEQTests.FromSqlRaw<UEQTest>(@"SELECT * FROM UEQTests WHERE TestpersonId == 1;").ToList<UEQTest>();
            if (vis == null)
            {
                return NotFound();
            }
            return View(vis);
        }

   // GET: SUSTest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> createVisAWIs(IFormCollection form)
        {
            if (form == null || _context.Testpersons == null)
            {
                return NotFound();
            }
            // var data = new List<SUSTest>();
            var temp_Ids = form["item.id"];
            var temp_Questions = form["item.Question"];
            var temp_DisagreeEtAll = form["item.DisagreeEtAll"];
            var temp_Disagree = form["item.Disagree"];
            var temp_DisagreeRather = form["item.DisagreeRather"];
            var temp_Neutrals = form["item.Neutral"];
            var temp_AgreeRather = form["item.AgreeRather"];
            var temp_Agree = form["item.Agree"];
            var temp_AgreeEtAll = form["item.AgreeEtAll"];

            for (int i = 0; i < form["item.id"].Count(); i++)
            {
                var erg = _context.Find<VisAWITest>(Convert.ToInt32(temp_Ids[i]));
                erg.Question = temp_Questions[i];
                erg.DisagreeEtAll = ConvertToBool(temp_DisagreeEtAll[i]);
                erg.Disagree = ConvertToBool(temp_Disagree[i]);
                erg.DisagreeRather = ConvertToBool(temp_DisagreeRather[i]);
                erg.Neutral = ConvertToBool(temp_Neutrals[i]);
                erg.AgreeRather = ConvertToBool(temp_AgreeRather[i]);
                erg.Agree = ConvertToBool(temp_Agree[i]);
                erg.AgreeEtAll = ConvertToBool(temp_AgreeEtAll[i]);
                if (ModelState.IsValid)
                {
                    _context.Update(erg);
                    await _context.SaveChangesAsync();
                }
            }
            return View("~/Views/Home/Index.cshtml");
        }


 // GET: SUSTest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> createUEQs(IFormCollection form)
        {
            if (form == null || _context.Testpersons == null)
            {
                return NotFound();
            }
            // var data = new List<SUSTest>();
            var temp_Ids = form["item.id"];
            var temp_LeftWord = form["item.LeftWord"];
            var temp_RightWord = form["item.RightWord"];
            var temp_one = form["item.one"];
            var temp_two = form["item.two"];
            var temp_three = form["item.three"];
            var temp_four = form["item.four"];
            var temp_five = form["item.five"];
            var temp_six = form["item.six"];
            var temp_seven = form["item.seven"];

            for (int i = 0; i < form["item.id"].Count(); i++)
            {
                var erg = _context.Find<UEQTest>(Convert.ToInt32(temp_Ids[i]));
                erg.LeftWord = temp_LeftWord[i];
                erg.RightWord = temp_RightWord[i];
                erg.one = ConvertToBool(temp_one[i]);
                erg.two = ConvertToBool(temp_two[i]);
                erg.three = ConvertToBool(temp_three[i]);
                erg.four = ConvertToBool(temp_four[i]);
                erg.five = ConvertToBool(temp_five[i]);
                erg.six = ConvertToBool(temp_six[i]);
                erg.seven = ConvertToBool(temp_seven[i]);
                if (ModelState.IsValid)
                {
                    _context.Update(erg);
                    await _context.SaveChangesAsync();
                }
            }
            return View("~/Views/Home/Index.cshtml");
        }

         // GET: SUSTest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateForm(IFormCollection form)
        {
            if (form == null || _context.Testpersons == null)
            {
                return NotFound();
            }
            var data = new List<SUSTest>();
            var temp_Ids = form["item.id"];
            var temp_Questions = form["item.Question"];
            var temp_SDisagrees = form["item.StronglyDisagree"];
            var temp_Disagrees = form["item.Disagree"];
            var temp_Neutrals = form["item.Neutral"];
            var temp_Agrees = form["item.Agree"];
            var temp_SAgrees = form["item.StronglyAgree"];

            for (int i = 0; i < form["item.id"].Count(); i++)
            {
                var erg = _context.Find<SUSTest>(Convert.ToInt32(temp_Ids[i]));
                erg.Question = temp_Questions[i];
                erg.StronglyDisagree = ConvertToBool(temp_SDisagrees[i]);
                erg.Disagree = ConvertToBool(temp_Disagrees[i]);
                erg.Neutral = ConvertToBool(temp_Neutrals[i]);
                erg.Agree = ConvertToBool(temp_Agrees[i]);
                erg.StronglyAgree = ConvertToBool(temp_SAgrees[i]);
                if (ModelState.IsValid)
                {
                    _context.Update(erg);
                    await _context.SaveChangesAsync();
                }
            }
            return View("~/Views/Home/Index.cshtml");
        }


        private bool ConvertToBool(string temp){
            bool erg = false;
            if (temp.Equals("true"))
            {
                erg = true;
            }else if(temp.Equals("false")){
                erg= false;
            }
            return erg;
        }


        // GET: Testperson/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Testpersons == null)
            {
                return NotFound();
            }

            var testperson = await _context.Testpersons
                .FirstOrDefaultAsync(m => m.Id == id);
            if (testperson == null)
            {
                return NotFound();
            }

            return View(testperson);
        }

        // GET: Testperson/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Testperson/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,anonymName")] Testperson testperson)
        {
            if (ModelState.IsValid)
            {
                _context.Add(testperson);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(testperson);
        }

        // GET: Testperson/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Testpersons == null)
            {
                return NotFound();
            }

            var testperson = await _context.Testpersons.FindAsync(id);
            if (testperson == null)
            {
                return NotFound();
            }
            return View(testperson);
        }

        // POST: Testperson/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,anonymName")] Testperson testperson)
        {
            if (id != testperson.Id)
            {
                return NotFound();
            }

Server/Views/Testperson/Create.cshtml
@model UIAutomate.Models.Testperson

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Testperson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="anonymName" class="control-label"></label>
                <input asp-for="anonymName" class="form-control" />
                <span asp-validation-for="anonymName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/Testperson/Delete.cshtml
@model UIAutomate.Models.Testperson

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Testperson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.anonymName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.anonymName)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Server/Views/Testperson/Details.cshtml
@model UIAutomate.Models.Testperson

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Testperson</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.anonymName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.anonymName)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Server/Views/Testperson/Edit.cshtml
@model UIAutomate.Models.Testperson

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Testperson</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="anonymName" class="control-label"></label>
                <input asp-for="anonymName" class="form-control" />
                <span asp-validation-for="anonymName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/Testperson/Introduction.cshtml
@* @model UIAutomate.Models.Testperson *@

@{
    ViewData["Title"] = "Introduction";
}
<h1>@ViewData["Title"]</h1>

@* <p>This page show the UI Introduction.</p> *@


@* <h1>Introduction</h1> *@

<h2>Goals/ Explanation</h2>

<p>The aim of this test is to assess the website in terms of usability, user experience and aesthetics.
In order to achieve this, you will be given a number of tasks to be implemented in the website at the beginning. After completing the tasks, you will be presented with 3 questionnaires.
The first questionnaire aims at evaluating the usability of the application, while the following questionnaire is intended for evaluating the user experience (UX) of the application. The last questionnaire deals with the visual aesthetics of the application.
By analysing the audio recording of the Thinking Loud method, misinterpretations of the application are revealed and can be improved by changing the design or a different arrangement of the elements.
</p>

<h2>Procedure</h2>
<ol>
    <h3>
        <li> Description</li>
    </h3>  
    <h3>
        <li>Explanation</li>
    </h3>
   
    <ul> 
        <li> Introduction to the Thinking Loud method by means of an example </li>
            <iframe width="420" height="345" src="https://www.youtube.com/watch?v=g34tOmyKaMM?autoplay=0&mute=0">
            </iframe>   
        <li> declaration of consent for audio recording </li>
    </ul>

    <h3>
        <li> Warm-up phase</li>
    </h3>
    <p>Subject's previous expectations of the application and expectations of the application.</p>

    <h3> Tasks of the usability test </h3>
    <ol>
        <b>Warm up tasks</b>
        <li>Task: Find some specifications about the sensor module. </li>
        <li>Task: Find out who the contact person for questions is. </li>
        @* <li>Task: Find the button to change the language of the website. </li> *@

        @* <b>Imagine you want to mount a sensor module on an excavator.</b> *@
        <li>Taks: Log into the system.</li>
        <li>Taks: How many percent do all machines spend in the activity "Digging"?</li>
        <li>Taks: Take a closer look at the EC950F machine and find out what percentage of the time this machine spends in the activity "Ideling" on average.</li>
        <li>Taks: What are the average costs per working hour for all machines?</li>

        <b>Imagine you want to install a sensor node on a machine. </b>
        <li>Task: Add a new Maschine. </li>
        <li>Task: Create a new activity to the machine "EC950F". </li>
        <li>Task: Add a new sensor to the machine "EC950F" at position 1. </li>

        <li>Task: Add the activity Movement to the parameter X Axis of the newly added senornode.</li>
        @* <li>Task: You want to look at the data generated by the new sensor. Find the diagram that shows the data for this purpose  </li> *@
        <li>Task: You have a problem and would like to contact support. Find a way to do that.</li>  
    </ol>

    <h3>
        <li>Questionnaires Final questions/post-survey</li>
    </h3>    
        <p>The three questionnaires are presented to you below.</p>

    @* <div class="row">
        <div class="col-md-4">
            <form asp-action="Create" asp-controller="Testperson">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="anonymName" class="control-label"></label>
                    <input asp-for="anonymName" class="form-control" />
                    <span asp-validation-for="anonymName" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div> *@



</ol>

Server/Views/Testperson/SUSResults.cshtml
@model IEnumerable<UIAutomate.Models.SUSTest>

@{
    ViewData["Title"] = "System Usability Scale (SUS)";
}

<h1>System Usability Scale (SUS)</h1>

<h4>Please rate on the following scale to what extent you agree with the statements.</h4>
<hr />
@using(Html.BeginForm("CreateForm", "Testperson", FormMethod.Post, new { role = "form" }))
{
    <form asp-action="CreateForm" ,controller="SUSTest", formaction>
        <div class="row">
        <div class="col-md-4">
            <table>
            <tr>
                <thead>
                    <tr>
                        <th></th> 
                        <th> <div id="valid1">Strongly disagree</div>     </th> 
                        <th> <div id="valid2">Disagree</div> </th> 
                        <th> <div id="valid3">Neutral</div></th>
                        <th> <div id="valid4">Agree</div></th>
                        <th> <div id="valid5">Strongly agree</div> </th>
                    </tr>  
                </thead>
                <tbody>
                @foreach (var item in Model as IEnumerable<UIAutomate.Models.SUSTest>) 
                {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @* <input type="hidden" asp-for="@item"  /> *@
                <input type="hidden" asp-for="@item.Id"  />
                <input type="hidden" asp-for="@item.Question"  />
                <tr>
                    <th>
                        @Html.DisplayFor(model => item.Question)
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.StronglyDisagree" type="checkbox" id="cb1" value="true" data-val=1/>
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Disagree" type="checkbox" id="cb2" value="false" /> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Neutral" type="checkbox" id="cb3" value="1"/>
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Agree"  type="checkbox" id="cb4" value="2"/> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.StronglyAgree"  type="checkbox" id="cb5" value="0"/>
                            </label>
                        </div>
                    </th>
                </tr>
                }
                </tbody> 
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/Testperson/UEQFormular.cshtml
@model IEnumerable<UIAutomate.Models.UEQTest>

@{
    ViewData["Title"] = "UEQ - User Experience Questionnaire";
}

<h1>UEQ - User Experience Questionnaire</h1>

<h4>For the assessment of the product, please fill out the following questionnaire. 
The questionnaire consists of pairs of contrasting attributes that may apply to 
the product. The circles between the attributes represent gradations between 
the opposites. You can express your agreement with the attributes by ticking 
the circle that most closely reflects your impression.
@* Example:
attractive        unattractive *@
This response would mean that you rate the application as more attractive
than unattractive.
Please decide spontaneously. Don’t think too long about your decision to 
make sure that you convey your original impression.
Sometimes you may not be completely sure about your agreement with a 
particular attribute or you may find that the attribute does not apply completely 
to the particular product. Nevertheless, please tick a circle in every line.
It is your personal opinion that counts. Please remember: there is no wrong or 
right answer!

Please assess the product now by ticking one circle per line.
</h4>
<hr />
@using(Html.BeginForm("CreateUEQs", "Testperson", FormMethod.Post, new { role = "form" }))
{
    <form asp-action="CreateUEQs" ,controller="SUSTest", formaction>
        <div class="row">
        <div class="col-md-4">
            <table>
            <tr>
                <thead>
                    <tr>
                        <th></th> 
                        <th> <div id="valid1">1</div>     </th> 
                        <th> <div id="valid2">2</div> </th> 
                        <th> <div id="valid3">3</div> </th> 
                        <th> <div id="valid4">4</div></th>
                        <th> <div id="valid5">5</div></th>
                        <th> <div id="valid6">6</div> </th>
                        <th> <div id="valid7">7</div> </th> 
                    </tr>  
                </thead>
                <tbody>
                @foreach (var item in Model as IEnumerable<UIAutomate.Models.UEQTest>) 
                {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @* <input type="hidden" asp-for="@item"  /> *@
                <input type="hidden" asp-for="@item.Id"  />
                <input type="hidden" asp-for="@item.LeftWord"  />
                <input type="hidden" asp-for="@item.RightWord"  />
                <tr>
                    <th>
                        @Html.DisplayFor(model => item.LeftWord)
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.one" type="checkbox" id="cb1" value="true"/>
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.two" type="checkbox" id="cb2"  /> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.three" type="checkbox" id="cb3" />
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.four" type="checkbox" id="cb4"/> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.five" type="checkbox" id="cb5" />
                            </label>
                        </div>
                    </th>
                     <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.six" type="checkbox" id="cb6" />
                            </label>
                        </div>
                    </th>
                     <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.seven" type="checkbox" id="cb7" />
                            </label>
                        </div>
                    </th>
                    <th>
                        @Html.DisplayFor(model => item.RightWord)
                    </th>
                </tr>
                }
                </tbody> 
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/Testperson/VisAWIFormular.cshtml
@model IEnumerable<UIAutomate.Models.VisAWITest>

@{
    ViewData["Title"] = "VisAWI - Visual Aesthetics of Website Inventory";
}

<h1>VisAWI - Visual Aesthetics of Website Inventory</h1>

<h4>Please  rate on a scale of 1 (strongly disagree) to 7 (strongly  agree) the  extent to which you agree with the following statements in  relation to  the application you have. 
    Thank you very much!
</h4>
<hr />
@using(Html.BeginForm("CreateVisAWIs", "Testperson", FormMethod.Post, new { role = "form" }))
{
    <form asp-action="CreateVisAWI" ,controller="SUSTest", formaction>
        <div class="row">
        <div class="col-md-4">
            <table>
            <tr>
                <thead>
                    <tr>
                        <th></th> 
                        <th> <div id="valid1">Disagree et all</div>     </th> 
                        <th> <div id="valid2">Disagree</div> </th> 
                        <th> <div id="valid3">Disagree rather</div> </th> 
                        <th> <div id="valid4">Neutral</div></th>
                        <th> <div id="valid5">Agree rather</div></th>
                        <th> <div id="valid6">Agree</div> </th>
                        <th> <div id="valid7">Agree er all</div> </th> 
                    </tr>  
                </thead>
                <tbody>
                @foreach (var item in Model as IEnumerable<UIAutomate.Models.VisAWITest>) 
                {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @* <input type="hidden" asp-for="@item"  /> *@
                <input type="hidden" asp-for="@item.Id"  />
                <input type="hidden" asp-for="@item.Question"  />
                <tr>
                    <th>
                        @Html.DisplayFor(model => item.Question)
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.DisagreeEtAll" type="checkbox" id="cb1" />
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Disagree" type="checkbox" id="cb2"  /> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.DisagreeRather" type="checkbox" id="cb3" />
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Neutral" type="checkbox" id="cb4"/> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.AgreeRather" type="checkbox" id="cb5" />
                            </label>
                        </div>
                    </th>
                     <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Agree" type="checkbox" id="cb6" />
                            </label>
                        </div>
                    </th>
                     <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.AgreeEtAll" type="checkbox" id="cb7" />
                            </label>
                        </div>
                    </th>
                </tr>
                }
                </tbody> 
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}