Server/Models/SUSTest.cs
using System.Data;
using System.Threading.Tasks;
using MySqlConnector;
using System.ComponentModel.DataAnnotations;

namespace UIAutomate.Models{
    
    public class SUSTest
    {
        [Key]
        public int Id { get; set; }

        public string Question {get; set; }
        public bool StronglyDisagree {get; set;}
        public bool Disagree {get; set;}
        public bool Neutral {get; set;}
        public bool Agree {get; set;}
        public bool StronglyAgree {get; set;}

        // public int TestpersonId {get; set;}
        public Testperson Testperson {get; set; }


    }


     


}

Server/Controllers/SUSTestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using UIAutomate.Models;

namespace Server.Controllers
{
    public class SUSTestController : Controller
    {
        private readonly TestpersonContext _context;

        public SUSTestController(TestpersonContext context)
        {
            _context = context;
        }

        // GET: SUSTest
        // public async Task<IActionResult> Formular()
        // {
        //       return _context.Find()SUSTest != null ? 
        //                   View(await _context.Testpersons..ToListAsync()) :
        //                   Problem("Entity set 'SUSTestContext.SUSTest'  is null.");
        // }


        // public async Task<IActionResult> Introduction()
        // {
        //       return _context.SUSTest != null ? 
        //                   View(await _context.SUSTest.ToListAsync()) :
        //                   Problem("Entity set 'SUSTestContext.SUSTest'  is null.");
        // }

        // GET: SUSTest/Details/5
        // public async Task<IActionResult> Details(int? id)
        // {
        //     if (id == null || _context.SUSTest == null)
        //     {
        //         return NotFound();
        //     }

        //     var sUSTest = await _context.SUSTest
        //         .FirstOrDefaultAsync(m => m.Id == id);
        //     if (sUSTest == null)
        //     {
        //         return NotFound();
        //     }

        //     return View(sUSTest);
        // }

        // // GET: SUSTest/Create
        // public IActionResult Create()
        // {
        //     return View();
        // }

        // POST: SUSTest/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Question,StronglyDisagree,Disagree,Neutral,Agree,StronglyAgree")] SUSTest sUSTest)
        {
            if (ModelState.IsValid)
            {
                _context.Add(sUSTest);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(sUSTest);
        }

        // GET: SUSTest/Edit/5    duplicatet
        public async Task<IActionResult> SUSResults()
        {
            // if (id == null || _context.SUSTest == null)
            // {
            //     return NotFound();
            // }
//   return View(await _context.Testpersons.ToListAsync());

                                        //   await
            IEnumerable<SUSTest> sUSTest = _context.Testpersons.Find(1).SUSTests.AsEnumerable<SUSTest>();
            if (sUSTest == null)
            {
                return NotFound();
            }
            return View(sUSTest);
        }


        // GET: SUSTest/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateForm(IFormCollection form)
        {
            if (form == null || _context.Testpersons == null)
            {
                return NotFound();
            }
            var data = new List<SUSTest>();
            var temp_Ids = form["item.id"];
            var temp_Questions = form["item.Question"];
            var temp_SDisagrees = form["item.StronglyDisagree"];
            var temp_Disagrees = form["item.Disagree"];
            var temp_Neutrals = form["item.Neutral"];
            var temp_Agrees = form["item.Agree"];
            var temp_SAgrees = form["item.StronglyAgree"];

            for (int i = 0; i < form["item.id"].Count(); i++)
            {
                var erg = _context.Find<SUSTest>(Convert.ToInt32(temp_Ids[i]));
                erg.Question = temp_Questions[i];
                erg.StronglyDisagree = ConvertToBool(temp_SDisagrees[i]);
                erg.Disagree = ConvertToBool(temp_Disagrees[i]);
                erg.Neutral = ConvertToBool(temp_Neutrals[i]);
                erg.Agree = ConvertToBool(temp_Agrees[i]);
                erg.StronglyAgree = ConvertToBool(temp_SAgrees[i]);
                if (ModelState.IsValid)
                {
                    _context.Update(erg);
                    await _context.SaveChangesAsync();
                }
            }
            return View("~/Views/Home/Index.cshtml");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateVisAWI(IFormCollection form){


            return View("~/Views/Home/Index.cshtml");
        }





        private bool ConvertToBool(string temp){
            bool erg = false;
            if (temp.Equals("true"))
            {
                erg = true;
            }else if(temp.Equals("false")){
                erg= false;
            }
            return erg;
        }







        // GET: SUSTest/Edit/5

        // public async Task<IActionResult> Edit(int? id)
        // {
        //     if (id == null || _context.SUSTest == null)
        //     {
        //         return NotFound();
        //     }

        //     var sUSTest = await _context.SUSTest.FindAsync(id);
        //     if (sUSTest == null)
        //     {
        //         return NotFound();
        //     }
        //     return View(sUSTest);
        // }

        // POST: SUSTest/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        // [HttpPost]
        // [ValidateAntiForgeryToken]
        // public async Task<IActionResult> Edit(int id, [Bind("Id,Question,StronglyDisagree,Disagree,Neutral,Agree,StronglyAgree")] SUSTest sUSTest)
        // {
        //     if (id != sUSTest.Id)
        //     {
        //         return NotFound();
        //     }

        //     if (ModelState.IsValid)
        //     {
        //         try
        //         {
        //             _context.Update(sUSTest);
        //             await _context.SaveChangesAsync();
        //         }
        //         catch (DbUpdateConcurrencyException)
        //         {
        //             if (!SUSTestExists(sUSTest.Id))
        //             {
        //                 return NotFound();
        //             }
        //             else
        //             {
        //                 throw;
        //             }
        //         }
        //         return RedirectToAction(nameof(Index));
        //     }
        //     return View(sUSTest);
        // }

        // GET: SUSTest/Delete/5
        // public async Task<IActionResult> Delete(int? id)
        // {
        //     if (id == null || _context.SUSTest == null)
        //     {
        //         return NotFound();
        //     }

        //     var sUSTest = await _context.SUSTest
        //         .FirstOrDefaultAsync(m => m.Id == id);
        //     if (sUSTest == null)
        //     {
        //         return NotFound();
        //     }

        //     return View(sUSTest);
        // }

    //     // POST: SUSTest/Delete/5
    //     [HttpPost, ActionName("Delete")]
    //     [ValidateAntiForgeryToken]
    //     public async Task<IActionResult> DeleteConfirmed(int id)
    //     {
    //         if (_context.SUSTest == null)
    //         {
    //             return Problem("Entity set 'SUSTestContext.SUSTest'  is null.");
    //         }
    //         var sUSTest = await _context.SUSTest.FindAsync(id);
    //         if (sUSTest != null)
    //         {
    //             _context.SUSTest.Remove(sUSTest);
    //         }
            
    //         await _context.SaveChangesAsync();
    //         return RedirectToAction(nameof(Index));
    //     }

    //     private bool SUSTestExists(int id)
    //     {
    //       return (_context.SUSTest?.Any(e => e.Id == id)).GetValueOrDefault();
    //     }
    }
}

Server/Views/SUSTest/Create.cshtml
@model UIAutomate.Models.SUSTest

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>SUSTest</h4>
<hr />
@using (Html.BeginForm("Index", "Home", FormMethod.Post))
{
    <div class="row">
        <div class="col-md-4">
            <form asp-action="Create">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <div class="form-group">
                    <label asp-for="Question" class="control-label"></label>
                    <input asp-for="Question" class="form-control" />
                    <span asp-validation-for="Question" class="text-danger"></span>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="StronglyDisagree" /> @Html.DisplayNameFor(model => model.StronglyDisagree)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Disagree" /> @Html.DisplayNameFor(model => model.Disagree)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Neutral" /> @Html.DisplayNameFor(model => model.Neutral)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="Agree" /> @Html.DisplayNameFor(model => model.Agree)
                    </label>
                </div>
                <div class="form-group form-check">
                    <label class="form-check-label">
                        <input class="form-check-input" asp-for="StronglyAgree" /> @Html.DisplayNameFor(model => model.StronglyAgree)
                    </label>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/SUSTest/Delete.cshtml
@model UIAutomate.Models.SUSTest

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>SUSTest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StronglyDisagree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StronglyDisagree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disagree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disagree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Neutral)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Neutral)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StronglyAgree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StronglyAgree)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Server/Views/SUSTest/Details.cshtml
@model UIAutomate.Models.SUSTest

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>SUSTest</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Question)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Question)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StronglyDisagree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StronglyDisagree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Disagree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Disagree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Neutral)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Neutral)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Agree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Agree)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StronglyAgree)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StronglyAgree)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Server/Views/SUSTest/Edit.cshtml
@model UIAutomate.Models.SUSTest

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SUSTest</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Question" class="control-label"></label>
                <input asp-for="Question" class="form-control" />
                <span asp-validation-for="Question" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="StronglyDisagree" /> @Html.DisplayNameFor(model => model.StronglyDisagree)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Disagree" /> @Html.DisplayNameFor(model => model.Disagree)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Neutral" /> @Html.DisplayNameFor(model => model.Neutral)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Agree" /> @Html.DisplayNameFor(model => model.Agree)
                </label>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="StronglyAgree" /> @Html.DisplayNameFor(model => model.StronglyAgree)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Server/Views/SUSTest/Formular.cshtml
@model IEnumerable<UIAutomate.Models.SUSTest>

@* @model UIAutomate.Models.SUSTest *@

@{
    ViewData["Title"] = "System Usballity Scale (SUS)";
}
<h1>@ViewData["Title"]</h1>

<p>Please rate on the following scale to what extent you agree with the statements.</p>


<form method="post">
    <table>
        <tr>
            <thead>
                <tr>
                    <th></th> 
                    <th> <div id="valid1">Strongly disagree</div>     </th> 
                    <th> <div id="valid2">Disagree</div> </th> 
                    <th> <div id="valid3">Neutral</div></th>
                    <th> <div id="valid4">Agree</div></th>
                    <th> <div id="valid5">Strongly agree</div> </th>
                </tr>  
            </thead>
            <tbody>
                @foreach (var item in Model) {
                    <tr>
                        <th> @Html.DisplayFor(modelItem => item.Question)</th>
                        <div class= "checkbox">
                            <th><input type="checkbox" id="cb12" name="cb12" value='@Html.DisplayFor(modelItem => item.StronglyDisagree)'></th> 
                            <th><input type="checkbox" id="cb12" name="cb12" value='@Html.DisplayFor(modelItem => item.Disagree)'></th> 
                            <th><input type="checkbox" id="cb13" name="cb13" value='@Html.DisplayFor(modelItem => item.Neutral)'></th> 
                            <th><input type="checkbox" id="cb14" name="cb14" value='@Html.DisplayFor(modelItem => item.Agree)'></th>
                            <th><input type="checkbox" id="cb15" name="cb15" value='@Html.DisplayFor(modelItem => item.StronglyAgree)'></th>
                            @* <div class="form-group">
                                <input type="submit" value="Update" class="btn btn-primary" />
                            </div> *@
                        </div>
                    </tr>
                }
          
        </tr>
    </table>
</form>


<div class="form-group">
    <input type="submit" value="Edit" class="btn btn-primary" />
</div>

Server/Views/SUSTest/Index.cshtml
@model IEnumerable<UIAutomate.Models.SUSTest>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Question)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StronglyDisagree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Disagree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Neutral)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Agree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.StronglyAgree)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Question)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StronglyDisagree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Disagree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Neutral)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Agree)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.StronglyAgree)
            </td>
            @* <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td> *@
        </tr>
}
    </tbody>
</table>

Server/Views/SUSTest/SUSResults.cshtml
@* @model UIAutomate.Models.SUSTest *@
@model IEnumerable<UIAutomate.Models.SUSTest>

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SUSTest</h4>
<hr />
@using(Html.BeginForm("CreateForm", "SUSTest", FormMethod.Post, new { role = "form" }))
{
    <form asp-action="CreateForm" >
        <div class="row">
        <div class="col-md-4">
            <table>
            <tr>
                <thead>
                    <tr>
                        <th></th> 
                        <th> <div id="valid1">Strongly disagree</div>     </th> 
                        <th> <div id="valid2">Disagree</div> </th> 
                        <th> <div id="valid3">Neutral</div></th>
                        <th> <div id="valid4">Agree</div></th>
                        <th> <div id="valid5">Strongly agree</div> </th>
                    </tr>  
                </thead>
                <tbody>
                @foreach (var item in Model as IEnumerable<UIAutomate.Models.SUSTest>) 
                {
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                @* <input type="hidden" asp-for="@item"  /> *@
                <input type="hidden" asp-for="@item.Id"  />
                <input type="hidden" asp-for="@item.Question"  />
                <tr>
                    <th>
                        @Html.DisplayFor(model => item.Question)
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.StronglyDisagree" type="checkbox" id="cb1" />
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Disagree" type="checkbox" id="cb2"  /> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Neutral" type="checkbox" id="cb3" />
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.Agree" type="checkbox" id="cb4"/> 
                            </label>
                        </div>
                    </th>
                    <th>
                        <div class="form-group form-check">
                            <label class="form-check-label">
                                <input class="form-check-input" asp-for="@item.StronglyAgree" type="checkbox" id="cb5" />
                            </label>
                        </div>
                    </th>
                </tr>
                }
                </tbody> 
                <div class="form-group">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        </div>
    </form>
}
<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}